<?php

/**
 * @file
 * Contains cw_ie_gifts_test.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function cw_ie_gifts_test_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the cw_ie_gifts_test module.
    case 'help.page.cw_ie_gifts_test':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('FLC Gifts Test (IE)') . '</p>';
      return $output;

    default:
  }
}
