<?php

/**
 * @file
 * Contains cw_donations_event_codes.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function cw_donations_event_codes_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the cw_donations_event_codes module.
    case 'help.page.cw_donations_event_codes':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}
