<?php

/**
 * @file
 * Contains falcon_gifts_api.module.
 */

use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function falcon_gifts_api_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the falcon_gifts_api module.
    case 'help.page.falcon_gifts_api':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Common improvements and enhancements for JSON API.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_entity_base_field_info().
 */
function falcon_gifts_api_entity_base_field_info(EntityTypeInterface $entity_type) {
  $fields = [];
  if ($entity_type->id() == 'menu_link_content') {
    $fields['url'] = BaseFieldDefinition::create('string')
      ->setLabel(t('URL'))
      ->setDescription(t('The URL of the menu link.'))
      ->setComputed(TRUE)
      ->setQueryable(FALSE);
  }
  return $fields;
}
