version: '2'
services:

  ##########################
  ### MAIN FRONTEND ########
  ##########################

  fe_main:
    image: node:8.9-alpine
    ports:
      - "3001:3000"
    working_dir: /app
    command: sh -c 'yarn install && yarn run start:dev'
    labels:
      - 'traefik.backend=fe_main'
      - 'traefik.port=3000'

  ##########################
  ### GIFTS FRONTEND #######
  ##########################

  fe_gifts:
    image: node:8.9-alpine
    depends_on:
      - api_bus
    ports:
      - "3000"
    working_dir: /app
    command: sh -c 'yarn install && yarn run start'
    labels:
      - 'traefik.backend=fe_gifts'
      - 'traefik.port=3000'

  ##########################
  ####### API BUS ##########
  ##########################

  api_bus:
    image: webdevops/php-nginx:alpine-3-php7
    depends_on:
      - be_gifts_nginx
      - be_donations_nginx
    environment:
      WEB_DOCUMENT_ROOT: /app/public
    working_dir: /app
    labels:
      - 'traefik.backend=api_bus'
      - 'traefik.port=80'

  ##########################
  ### GIFTS BACKEND ########
  ##########################

  be_gifts:
    image: wodby/drupal-php:7.1-dev-4.2.3
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      DB_HOST: drupal
      DB_USER: drupal
      DB_PASSWORD: drupal
      DB_NAME: drupal
      DB_DRIVER: mysql

  be_gifts_mariadb:
    image: wodby/mariadb:10.2-3.1.3
    stop_grace_period: 30s
    environment:
      MYSQL_ROOT_PASSWORD: drupal
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal

  be_gifts_nginx:
    image: wodby/drupal-nginx:8-1.13-4.0.3
    depends_on:
      - be_gifts
    environment:
      NGINX_STATIC_CONTENT_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: be_gifts
      NGINX_SERVER_ROOT: /var/www/html/web
    labels:
      - 'traefik.backend=be_gifts_nginx'
      - 'traefik.port=80'

  be_gifts_pma:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: be_gifts_mariadb
      PMA_USER: drupal
      PMA_PASSWORD: drupal
      PHP_UPLOAD_MAX_FILESIZE: 1G
      PHP_MAX_INPUT_VARS: 1G
    labels:
      - 'traefik.backend=be_gifts_pma'
      - 'traefik.port=80'


  ##########################
  ### DONATIONS BACKEND ####
  ##########################

  be_donations:
    image: wodby/drupal-php:7.1-dev-4.2.3
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      DB_HOST: drupal
      DB_USER: drupal
      DB_PASSWORD: drupal
      DB_NAME: drupal
      DB_DRIVER: mysql

  be_donations_mariadb:
    image: wodby/mariadb:10.2-3.1.3
    stop_grace_period: 30s
    environment:
      MYSQL_ROOT_PASSWORD: drupal
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal

  be_donations_nginx:
    image: wodby/drupal-nginx:8-1.13-4.0.3
    depends_on:
      - be_donations
    environment:
      NGINX_STATIC_CONTENT_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: be_donations
      NGINX_SERVER_ROOT: /var/www/html/web
    labels:
      - 'traefik.backend=be_donations_nginx'
      - 'traefik.port=80'

  be_donations_pma:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: be_donations_mariadb
      PMA_USER: drupal
      PMA_PASSWORD: drupal
      PHP_UPLOAD_MAX_FILESIZE: 1G
      PHP_MAX_INPUT_VARS: 1G
    labels:
      - 'traefik.backend=be_donations_pma'
      - 'traefik.port=80'

  #########################
  ###### MAILHOG ##########
  #########################

  mailhog:
    image: mailhog/mailhog

  #########################
  ###### TRAEFIK ##########
  #########################

  traefik:
    image: traefik
    command: -c /dev/null --web --docker --logLevel=INFO
    ports:
      - '80:80'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
