<?php

/**
 * @file
 * Contains commerce_paypal_button.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function commerce_paypal_button_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the commerce_paypal_button module.
    case 'help.page.commerce_paypal_button':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('PayPal Express Checkout Integration for Commerce') . '</p>';
      return $output;

    default:
  }
}
