<?php

/**
 * @file
 * Contains cw_gifts_cards.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function cw_gifts_cards_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the cw_gifts_cards module.
    case 'help.page.cw_gifts_cards':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Postal and E-cards for Gifts.') . '</p>';
      return $output;

    default:
  }
}
