<?php

/**
 * @file
 * Contains cw_event_codes_migrate.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function cw_event_codes_migrate_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the cw_event_codes_migrate module.
    case 'help.page.cw_event_codes_migrate':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Event Codes Migrate CSV') . '</p>';
      return $output;

    default:
  }
}
