<?php

use Drupal\views\ViewExecutable;
use Drupal\views\Plugin\views\query\QueryPluginBase;

/**
 * Implements hook_cron().
 */
function falcon_exports_cron() {
  \Drupal::service('falcon_exports.cron')
    ->createExportEntities();
}

/**
 * Implements hook_views_query_alter().
 *
 * This is stolen from drupal.org, see
 * https://www.drupal.org/node/2819603#comment-12066418
 *
 * Needed to avoid duplicate customer profiles in views
 * in case if there are several orders from the same email.
 */
function falcon_exports_views_query_alter(ViewExecutable $view, QueryPluginBase $query) {
  switch ($view->id()) {
    case 'exports_gifts_order_list':
      // Make sure the correct billing profile information is retrieved.
      // Join to the commerce_order table instead of the user table for the profile id.
      $profile_table = $query->getTableInfo('profile_users_field_data');

      if (isset($profile_table['join'])) {
        $profile_table['join']->field = 'profile_id';
        $profile_table['join']->leftTable = 'commerce_order';
        $profile_table['join']->leftField = 'billing_profile__target_id';
      }
      break;
  }
}
