<?php

/**
 * @file
 * Contains falcon_mail.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function falcon_mail_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the falcon_mail module.
    case 'help.page.falcon_mail':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('E-mail customisations for Falcon') . '</p>';
      return $output;

    default:
  }
}


/**
 * Implements hook_mandrill_mail_alter().
 */
function falcon_mail_mandrill_mail_alter(&$mandrill_params, $message) {

  // Convert system emails into HTML if Mandrill is used.
  $message_ids = [
    'contact_page_mail',
    'user_password_reset',
    'user_register_admin_created',
  ];

  if (in_array($mandrill_params['message']['id'], $message_ids)) {
    $mandrill_params['message']['html'] = nl2br($mandrill_params['message']['html']);
  }
}

/**
 * Implements hook_theme().
 */
function falcon_mail_theme($existing, $type, $theme, $path) {
  return [
    'falcon_mail_commerce_order_receipt_gift_corporate' => [
      'variables' => [
        'order_entity' => NULL,
        'order_url' => NULL,
        'billing_information' => NULL,
        'shipping_information' => NULL,
        'payment_method' => NULL,
        'totals' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_mail().
 *
 * Captures the outgoing mail and sets appropriate message body and headers.
 */
function falcon_mail_mail($key, &$message, $params) {
  if (isset($params['headers'])) {
    $message['headers'] = array_merge($message['headers'], $params['headers']);
  }

  $message['from'] = $params['from'];
  $message['subject'] = $params['subject'];
  $message['body'][] = $params['body'];
}
