<?php

/**
 * @file
 * Contains cw_gifts_cards.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function cw_gifts_cards_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the cw_gifts_cards module.
    case 'help.page.cw_gifts_cards':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Postal and E-cards for Gifts.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_cron().
 */
function cw_gifts_cards_cron() {
  \Drupal::service('cw_gifts_cards.mail_sender')->sendScheduled();
}

/**
 * Implements hook_theme().
 */
function cw_gifts_cards_theme() {
  $theme = [];
  $theme['gift_card_config'] = array(
    'render element' => 'elements',
    'file' => 'gift_card_config.page.inc',
    'template' => 'gift_card_config',
  );
  $theme['gift_card_config_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'gift_card_config.page.inc',
  ];
  $theme['ecard_item'] = array(
    'render element' => 'elements',
    'file' => 'ecard_item.page.inc',
    'template' => 'ecard_item',
  );
  $theme['ecard_item_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'ecard_item.page.inc',
  ];
  $theme['ecard_item_mail'] = [
    'variables' => [
      'ecard_item_entity' => NULL,
      'friends_name' => NULL,
      'sender_name' => NULL,
      'button_url' => NULL,
    ],
  ];

  return $theme;
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function cw_gifts_cards_theme_suggestions_gift_card_config(array $variables) {
  $suggestions = array();
  $entity = $variables['elements']['#gift_card_config'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'gift_card_config__' . $sanitized_view_mode;
  $suggestions[] = 'gift_card_config__' . $entity->bundle();
  $suggestions[] = 'gift_card_config__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'gift_card_config__' . $entity->id();
  $suggestions[] = 'gift_card_config__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function cw_gifts_cards_theme_suggestions_ecard_item(array $variables) {
  $suggestions = array();
  $entity = $variables['elements']['#ecard_item'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'ecard_item__' . $sanitized_view_mode;
  $suggestions[] = 'ecard_item__' . $entity->bundle();
  $suggestions[] = 'ecard_item__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'ecard_item__' . $entity->id();
  $suggestions[] = 'ecard_item__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}

/**
 * Implements hook_mail().
 *
 * Captures the outgoing mail and sets appropriate message body and headers.
 */
function cw_gifts_cards_mail($key, &$message, $params) {
  if (isset($params['headers'])) {
    $message['headers'] = array_merge($message['headers'], $params['headers']);
  }

  $message['from'] = $params['from'];
  $message['subject'] = $params['subject'];
  $message['body'][] = $params['body'];
}

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function cw_gifts_cards_ecard_item_insert(\Drupal\cw_gifts_cards\Entity\EcardItem $ecardItem) {
  // Only normal gifts are supported.
  if ($ecardItem->bundle() != 'gift') {
    return FALSE;
  }

  if (!$ecardItem->canSendNow()) {
    return FALSE;
  }

  // Sender service will determine if email should be send immediately
  // and will send it if the order is valid.
  \Drupal::service('cw_gifts_cards.mail_sender')->send($ecardItem);
}
