<?php

/**
 * @file
 * Contains falcon_redirect.module.
 */

use Drupal\Core\Access\AccessResult;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Session\AccountInterface;

/**
 * Implements hook_ENTITY_TYPE_access().
 */
function falcon_redirect_redirect_access(EntityInterface $entity, $operation, AccountInterface $account) {
  if ($operation == 'view') {
    return AccessResult::allowed();
  }

  return AccessResult::neutral();
}

/**
 * Implements hook_entity_base_field_info().
 */
function falcon_redirect_entity_base_field_info(EntityTypeInterface $entity_type) {
  $fields = [];
  if ($entity_type->id() == 'redirect') {
    $fields['redirect_url'] = BaseFieldDefinition::create('string')
      ->setLabel(t('URL'))
      ->setDescription(t('The URL of the redirect target.'))
      ->setComputed(TRUE)
      ->setQueryable(FALSE);
  }
  return $fields;
}
